export interface User {
    accountType : String ,
    alreadyRegister : String , 
     netIncomeMonthly : String, 
    privateHealth: String,
     numberOfDependent: String ,
     MaintanceObligation : String ,
     positionProfession :String ,
     firstName : String,
     lastName : String,
     dateOfBirth : String,
     materialStatus : String,
     placeOfBirth : String,
     country : String,
     plz : String,
     city : String,
     phoneNumber : String,
     streetAndNumber : String,
     email : String,
     transactions : boolean,
     moneyLaundering : boolean ,
     schufa: boolean,
     custody : boolean ,
     isDownloaded : boolean,
     isDownloaded2 : boolean,

}